### ISSUE TITLE
crank's `help` command.

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/crank#485]
The following commands were executed on Windows:

```
>crank compare --help
Unrecognized option '--help'

>crank compare -?
Unrecognized option '-?'

>crank compare -h
Unrecognized option '-h'
```

The documentation for the `crank` command states the following:

```
...
Commands:
  compare                  Compares result files

Run 'crank [command] -?|-h|--help' for more information about a command.
...
```

I ran the following command to install `crank`.

```
>dotnet tool update Microsoft.Crank.Controller --version "0.2.0-*" --global
```

**Comment by catcherwong** [comment]
The subcommand `compare` doesn't show the help information due to the configuration.

https://github.com/dotnet/crank/blob/47346489d7b4096962b1aaa4f5d8d11d55b7e0e9/src/Microsoft.Crank.Controller/Program.cs#L151

Based on https://natemcmaster.github.io/CommandLineUtils/docs/help-text.html#add-a-help-option-to-all-subcommands, set `inherited` to true can solve it.

```cs
app.HelpOption("-?|-h|--help", true); 
```

![done](https://user-images.githubusercontent.com/8394988/221854598-05ec51ea-873f-45ce-9627-27e090863e72.png)
