### ISSUE TITLE
Can Crank be run using CI/CD pipeline?

### ISSUE THREAD

**Issue by ribubrar** [dotnet/crank#490]
The problem I am facing when trying to run Crank in the pipeline is that one or the other is unrecognized out of two commands (crank and crank-agent).

I am using self hosted agents. Once the crank-agent is run, it keeps waiting for the job to be queued by the controller, and any following sequential commands in the same Agent pool would not get processed.
When I run the controller using another pool-agent, I have found that it sometimes doesn't recognize the command. And on other times, crank-agent is unrecognized.

So far, I have not been able to get both commands running at the same time.

**Comment by ronaldbarendse** [comment]
The recommended architecture is to run the controller and agent on different machines, so they don't fight for resources that can affect the benchmark results and also allows you to run multiple scenarios at the same time (on multiple agents).

That said,  you can install both controller and agent within a single CI/CD pipeline:

```powershell
dotnet tool install -g Microsoft.Crank.Controller --version "0.2.0-*"
dotnet tool install -g Microsoft.Crank.Agent --version "0.2.0-*"
```

And run the following PowerShell script that starts the agent in a new process (in the background), runs the specified scenarios and writes both agent log and benchmark results to disk:

```powershell
# Ensure artifacts directory exists
New-Item -Path artifacts -ItemType Directory -Force | Out-Null

# Start agent
$agent = Start-Process "crank-agent" -PassThru -RedirectStandardOutput artifacts/agent.log -RedirectStandardError artifacts/agent-error.log

# Scenarios to run
$scenarios = @(
	"hello"
)

# Start benchmarks
foreach ($scenario in $scenarios)
{
	crank --config hello.benchmarks.yml --scenario "$scenario" --profile local --json "artifacts/$scenario.json"
}

# Stop agent
Stop-Process $agent
```

You can then upload these log/JSON files as artifacts, so they're available for further processing, etc.

I have this working as a proof of concept using GitHub Actions, but each run returns slightly different results and because the build servers are continually updated/upgraded, won't produce usable results that can be compared over a longer period (also see this relevant blog-post: [Is GitHub Actions suitable for running benchmarks?](https://labs.quansight.org/blog/2021/08/)).
