### ISSUE TITLE
Modern ubuntu distros changed semantics of cgroup, breaking crank's cpuset

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/crank#586]
Crank depends on cgroup.v1 semantics, which does not work on cgroup.v2 semantics. 

            # on Ubuntu Linux >= 22.04 with cgroup.v2 you must follow this protocol
            # to disable some cgroup.v2 semantics that differ from cgroup.v1
            # crank depends on cgroup.v1 semantics.
            #     https://askubuntu.com/questions/1406329/how-to-run-cgexec-without-sudo-as-current-user-on-ubuntu-22-04-with-cgroups-v2
            # sudo vi /etc/default/grub
            # add to GRUB_CMDLINE_LINUX systemd.unified_cgroup_hierarchy=false
            #   sudo update-grub
            #   sudo reboot
            # You must then run crank as sudo on the linux worker machine, viz:
            #   sudo make MNT=/mnt/root start_load

**Comment by catcherwong** [comment]
I think crank can support both cgroup.v1 and cgroup.v2.

When the OS uses cgroup.v2, crank uses the semantics of cgroup.v2, otherwise cgroup.v1 is used.

`stat -fc %T /sys/fs/cgroup/`  can help us to ensure the version of cgroup, For cgroup v2, the output is `cgroup2fs`. For cgroup v1, the output is `tmpfs`.

Mapping between v1 and v2 that crank used.

| cgroup v1     | cgroup v2 |
| ----------- | ----------- |
| memory.limit_in_bytes | memory.max|
| cpu.cfs_period_us/cpu.cfs_quota_us   | cpu.max |
| cpuset.cpus | cpuset.cpus   |
| cpuset.mems | cpuset.mems   |
