### ISSUE TITLE
LocalFolder binaries are seeked in "\published"

### ISSUE THREAD

**Issue by sebastienros** [dotnet/crank#628]
Example:

```
crank.exe  --config C:\git\benchmarks\scenarios\plaintext.benchmarks.yml --application.source.project "" --application.source.repository "" --application.source.localFolder C:\git\benchmarks\src\Benchmarks\bin\Release\net7.0\win-x64\publish\app --application.executable Benchmarks.exe --scenario plaintext --profile aspnet-perf-win
```

Crank will try to execute "...\abcde\published" where the app is actually contained in "...\abcde".

**Comment by RobertHenry6bev** [comment]
I noticed recently, perhaps in my analysis, directories whose name contained `published/published` which smelled, but I didn't pursue that...

**Comment by caaavik-msft** [comment]
I think this issue is unrelated to the other issue, this is caused by empty strings not being forwarded correctly when it is a value of a dynamic argument.

On this line of code: https://github.com/dotnet/crank/blob/7114609ae6d36d50d8bbdf0dafc4035eebd9253a/src/Microsoft.Crank.Controller/Program.cs#L279-L282

When the arguments are being passed back in again, empty string arguments are not surrounded by quotes and so instead what happens is that `--application.source.project "" --application.source.repository ""` is being turned into `--application.source.project --application.source.repository`, so the project value is not set to empty and thus it thinks that the output is in the "published" directory.
